title: Sadat Shahriar
baseurl: ""
url: "https://sadat1971.github.io"

markdown: kramdown

nav:
  - title: About
    url: /
  - title: Publications
    url: /publications
  - title: Resume
    url: /resume
  - title: Blogs & Tutorials
    url: /blogs
  - title: Tech Links
    url: /tech-links

defaults:
  - scope:
      path: ""
    values:
      layout: default
